### ISSUE TITLE
"Network is unreachable" bug with Jellyfin integration

### ISSUE THREAD

**Issue by ddunne6** [MattsTechInfo/Meshnet#12]
I have setup a meshnet and pointed my jellyfin container to use it, see config below. The problem I have is that when I go to my browser to load `my-nord-vpn-dns.nord` on port 8096, nothing loads. The meshnet logs show that it is up and running fine, however the Jellyfin logs are giving back this `SocketException`. Any idea if I am missing something?
```
[14:00:22] [ERR] [30] Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from ************* to ************* 
System.Net.Sockets.SocketException (101): Network is unreachable
```

```
meshnet:
    image: ghcr.io/mattstechinfo/meshnet:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PUID=1000
      - PGID=1000
      - NORDVPN_TOKEN=*************
      - NORDVPN_ALLOW_PEER_ROUTING=*************
      - NORDVPN_ALLOW_PEER_LOCAL=*************
    hostname: meshnet   # Make sure hostname is set! Without it, every restart will add a new peer to your Meshnet.
    ports:
      - 8096:8096
      - 7359:7359/udp

jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ~/docker-services/jellyfin/config:/config
    restart: 'unless-stopped'
    network_mode: service:meshnet
```
