### ISSUE TITLE
  The VPN connection has failed

### ISSUE THREAD

**Issue by vampywiz17** [MattsTechInfo/Meshnet#15]
Hello there,

my problem that the container say The VPN connection has failed. My Docker host is a Alpine linux.

Here my docker compose:

```
version: "3"
services:
  meshnet:
    image: ghcr.io/mattstechinfo/meshnet:v3.17.0
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    hostname: alpine-virtual
    environment:
      - NORDVPN_TOKEN=$NORDVPN_TOKEN
      - NORDVPN_HEALTHCHECK_URL=$NORDVPN_HEALTHCHECK_URL
      - NORDVPN_HEALTHCHECK_INTERVAL=$NORDVPN_HEALTHCHECK_INTERVAL
      - NORDVPN_ALLOW_PEER_ROUTING=$NORDVPN_ALLOW_PEER_ROUTING
      - NORDVPN_ALLOW_PEER_LOCAL=$NORDVPN_ALLOW_PEER_LOCAL
      - NORDVPN_ALLOW_PEER_FILESHARE=$NORDVPN_ALLOW_PEER_FILESHARE
      - NORDVPN_ALLOW_PEER_REMOTE=$NORDVPN_ALLOW_PEER_REMOTE
```

the container log:

![image](https://github.com/MattsTechInfo/Meshnet/assets/14281430/2d3af4e3-7aed-4e95-bfb4-7c4e9b5c5c9e)
